name: ecl_croatia
dependencies:
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-blosc2=2.10.5
  - ca-certificates=2023.08.22
  - contourpy=1.0.5
  - cycler=0.11.0
  - et_xmlfile=1.1.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - importlib_resources=6.1.0
  - intel-openmp=2023.1.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.1
  - patsy=0.5.3
  - pillow=10.0.1
  - pip=23.3
  - py-cpuinfo=9.0.0
  - pyparsing=3.0.9
  - pytables=3.8.0
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - xz=5.4.2
  - zipp=3.11.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
prefix: C:\Modeling\Anaconda\envs\ecl_croatia
